version: '3'

services:
  deploy-mail:
    build: ./app
    depends_on:
      - mssql
    networks:
      - my-net
    ports:
      - 9788:8080
    volumes:
      - ./app/config:/usr/app/config
    environment:
      mssqlUrl: 'jdbc:sqlserver://newmacaque:3433;database=XCOLA'
      mssqlUser: 'sa'
      mssqlPwd: 'p@ssw0rd'

networks:
  my-net:
    driver: bridge

