version: '3'

services:
  deploy-mail:
    build: ./app
    networks:
      - my-net
    ports:
      - 9788:8080
    volumes:
      - ./app/config:/usr/app/config
    environment:
      mssqlUrl: 'jdbc:sqlserver://newmacaque:3433;database=XCOLA'
      mssqlUser: 'sa'
      mssqlPwd: 'p@ssw0rd'
    extra_hosts:
      - "newmacaque:192.168.27.44"
      - "macaque:192.168.27.45"

networks:
  my-net:
    driver: bridge

